# .github/workflows/ci.yml (수정)
name: CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'mcp_a2a_gateway/**'
      - 'tests/**'
      - 'pyproject.toml'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'mcp_a2a_gateway/**'
      - 'tests/**'
      - 'pyproject.toml'
      - '.github/workflows/**'
jobs:
  call_build_and_test_workflow:
    uses: ./.github/workflows/build-and-test.yml