# .github/workflows/publish.yml (수정)
name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/build-and-test.yml

  publish-to-pypi:
    needs: build # build 작업이 끝나야 실행돼요
    runs-on: ubuntu-latest
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: python-package
        path: dist/
        
    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Publish to PyPI
      env:
        UV_PUBLISH_USERNAME: __token__
        UV_PUBLISH_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: uv publish dist/*